# Generated by Django 4.0.5 on 2022-06-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('caseLead', models.CharField(max_length=100)),
                ('orgHandler', models.CharField(max_length=100)),
                ('assessmentType', models.CharField(choices=[('White Box:', 'White Box'), ('Grey Box:', 'Grey Box'), ('Black Box:', 'Black Box')], max_length=100)),
                ('scope', models.TextField()),
                ('logo', models.ImageField(upload_to='Cases/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
