# Generated by Django 4.0.5 on 2022-06-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cases_createdate_cases_lastupdate_alter_cases_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterField(
            model_name='cases',
            name='assessmentType',
            field=models.CharField(choices=[('White Box:', 'White Box'), ('Grey Box:', 'Grey Box'), ('Black Box:', 'Black Box')], default='Unspecified', max_length=100),
        ),
        migrations.AlterField(
            model_name='cases',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
