# Generated by Django 4.0.5 on 2022-06-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cases_options_alter_cases_assessmenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='logo',
            field=models.ImageField(upload_to='Cases/Logos'),
        ),
    ]
