# Generated by Django 4.0.5 on 2022-06-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cases_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools', models.TextField()),
                ('passive_sources', models.TextField()),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cases')),
            ],
            options={
                'verbose_name_plural': 'Recon',
            },
        ),
    ]
