# Generated by Django 4.0.5 on 2022-06-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proof', models.TextField()),
                ('severity', models.CharField(choices=[('', 'Severity'), ('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info')], max_length=100)),
                ('find_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('reference', models.TextField()),
                ('cvss_rating', models.IntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cases')),
            ],
            options={
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Cases/Screenshots')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issues')),
            ],
            options={
                'verbose_name_plural': 'Screenshots',
            },
        ),
    ]
