# Generated by Django 3.2.9 on 2022-06-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_issues_find_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='cvss_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='proof',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='reference',
            field=models.TextField(blank=True),
        ),
    ]
