# Generated by Django 3.2.9 on 2022-06-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_issues_screenshot_uploads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='proof',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='find_date',
        ),
        migrations.AddField(
            model_name='issues',
            name='proof_screenshot',
            field=models.ImageField(blank=True, upload_to='Cases/Screenshots'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='logo',
            field=models.ImageField(upload_to='Cases/<django.db.models.fields.CharField>/Logos'),
        ),
        migrations.DeleteModel(
            name='Screenshots',
        ),
    ]
