# Generated by Django 3.2.9 on 2022-07-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220630_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='severity',
            field=models.CharField(blank=True, choices=[('', 'Severity'), ('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info')], max_length=100),
        ),
    ]
