# Generated by Django 3.2.9 on 2022-07-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220709_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='cvss_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
