# Generated by Django 3.2.9 on 2022-08-02 21:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_issues_cvss_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='proof_screenshot',
        ),
        migrations.CreateModel(
            name='PoC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Cases/Screenshots', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jfif', 'exif', 'gif', 'tiff', 'bmp'])])),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issues')),
            ],
        ),
    ]
