# Generated by Django 3.2.9 on 2022-08-09 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220802_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='proof_screenshot',
            field=models.ImageField(blank=True, upload_to='Cases/Screenshots', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jfif', 'exif', 'gif', 'tiff', 'bmp'])]),
        ),
        migrations.DeleteModel(
            name='PoC',
        ),
    ]
