# Generated by Django 3.2.9 on 2022-08-20 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220818_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poc',
            options={'verbose_name_plural': 'Issue Proof of Concepts'},
        ),
        migrations.AddField(
            model_name='issues',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issues',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
