# Generated by Django 3.2.9 on 2022-10-14 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilitiesGeneral',
            fields=[
                ('title', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, choices=[('', 'Severity'), ('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info')], max_length=100)),
                ('reference', models.TextField(blank=True)),
                ('cvss_rating', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilitiesCWE',
            fields=[
                ('vulnerabilitiesgeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vulnerabilities.vulnerabilitiesgeneral')),
            ],
            bases=('vulnerabilities.vulnerabilitiesgeneral',),
        ),
        migrations.CreateModel(
            name='VulnerabilitiesEnterprise',
            fields=[
                ('vulnerabilitiesgeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vulnerabilities.vulnerabilitiesgeneral')),
            ],
            bases=('vulnerabilities.vulnerabilitiesgeneral',),
        ),
        migrations.CreateModel(
            name='VulnerabilitiesImported',
            fields=[
                ('vulnerabilitiesgeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vulnerabilities.vulnerabilitiesgeneral')),
            ],
            bases=('vulnerabilities.vulnerabilitiesgeneral',),
        ),
        migrations.CreateModel(
            name='VulnerabilitiesMobile',
            fields=[
                ('vulnerabilitiesgeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vulnerabilities.vulnerabilitiesgeneral')),
            ],
            bases=('vulnerabilities.vulnerabilitiesgeneral',),
        ),
        migrations.CreateModel(
            name='VulnerabilitiesOWAS',
            fields=[
                ('vulnerabilitiesgeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vulnerabilities.vulnerabilitiesgeneral')),
            ],
            bases=('vulnerabilities.vulnerabilitiesgeneral',),
        ),
    ]
