# Generated by Django 3.2.9 on 2022-10-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulnerabilitiescwe',
            options={'verbose_name_plural': 'CWE'},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilitiesenterprise',
            options={'verbose_name_plural': 'Enterprise'},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilitiesgeneral',
            options={'verbose_name_plural': 'General'},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilitiesimported',
            options={'verbose_name_plural': 'Imported'},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilitiesmobile',
            options={'verbose_name_plural': 'Mobile'},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilitiesowas',
            options={'verbose_name_plural': 'OWAS'},
        ),
    ]
