# Generated by Django 3.2.9 on 2022-10-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_auto_20221015_0154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VulnerabilitiesOWAS',
            new_name='VulnerabilitiesOWASP',
        ),
        migrations.AlterModelOptions(
            name='vulnerabilitiesowasp',
            options={'verbose_name_plural': 'OWASP'},
        ),
    ]
