# Generated by Django 3.2.9 on 2022-10-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0003_auto_20221015_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilitiesimported',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
